#!/bin/sh
#
#  This script ensures that daemons will not be started inside our
# chroot() installation.
#
# Steve
# --
# http://www.steve.org.uk/


TARGET=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Make sure we have a directory.
#
if [ ! -d "${TARGET}/usr/sbin" ]; then

    mkdir -p "${TARGET}/usr/sbin"

    logMessage "created missing directory: ${TARGET}/usr/sbin"
fi


#
#  Add the script.
#
echo '#!/bin/sh' >  ${TARGET}/usr/sbin/policy-rc.d
echo 'exit 101'  >> ${TARGET}/usr/sbin/policy-rc.d
chmod 755           ${TARGET}/usr/sbin/policy-rc.d



#
# Log our finish
#
logMessage Script $0 finished.

