#!/bin/sh
#
#  This script sets up the Yum for CentOS4.
#
# Steve
# --
# http://www.steve.org.uk/


TARGET=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Update yum
#
if [ ! -d ${TARGET}/proc ]; then
    mkdir -p ${TARGET}/proc
fi
mount -o bind /proc ${TARGET}/proc
chroot ${TARGET} /usr/bin/yum update
umount ${TARGET}/proc


#
#  Log our finish
#
logMessage Script $0 finished
