#!/bin/sh
#
#  This script sets up the Yum for CentOS4.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Update yum
#
if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
mount -o bind /proc ${prefix}/proc
chroot ${prefix} /usr/bin/yum update -y
umount ${prefix}/proc


#
#  Log our finish
#
logMessage Script $0 finished
