#!/bin/sh
#
#  Copy files from a 'skel' directory, if present, into the
# new images
#


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Copy "required" files from our host.
#
cp /etc/timezone    ${prefix}/etc
cp /etc/localtime   ${prefix}/etc


#
#  Log our finish
#
logMessage Script $0 finished
