#!/bin/sh
#
#  Copy files from a 'skel' directory, if present, into the
# new images
#


TARGET=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Copy "required" files from our host.
#
cp /etc/timezone    ${TARGET}/etc
cp /etc/localtime   ${TARGET}/etc


#
#  Log our finish
#
logMessage Script $0 finished
