#!/bin/sh
#
#  This script installs OpenSSH upon the new system.
#
# Steve
# --
# http://www.steve.org.uk/


TARGET=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting

#
# Install the OpenSSH server.
#
if [ ! -d ${TARGET}/proc ]; then
    mkdir -p ${TARGET}/proc
fi
mount -o bind /proc ${TARGET}/proc
chroot ${TARGET} /usr/bin/yum  -y install openssh-server passwd
umount ${TARGET}/proc


#
#  Log our finish
#
logMessage Script $0 finished
