#!/bin/sh
#
#  Ensure that either modules-init-tools or kmod is setup.
#
#  This is required in most setups.  But even if it isn't required it
# can't really do anything bad; just waste a bit of space.
#

TARGET=$1



#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting

#
#  Install either kmod or module-init-tools package.
#
if chroot ${TARGET} /usr/bin/apt-cache show module-init-tools >/dev/null 2>/dev/null; then
    if chroot ${TARGET} /usr/bin/apt-cache show module-init-tools | fgrep -qi transitional; then
        installDebianPackage ${TARGET} kmod
    else
        installDebianPackage ${TARGET} module-init-tools
    fi
else
    installDebianPackage ${TARGET} kmod
fi

#
#  Log our finish
#
logMessage Script $0 finished
