#!/bin/sh
#
#  Some root filesystems will require the installation of new packages
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1

#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Install any required packages for the given root filesystem
#
if [ $has_xfs -eq 1 ]; then
    installDebianPackage ${prefix} xfsprogs
fi
if [ $has_reiserfs -eq 1 ]; then
    installDebianPackage ${prefix} reiserfsprogs
fi
if [ $has_btrfs -eq 1 ]; then
    installDebianPackage ${prefix} btrfs-tools
fi


#
#  Log our finish
#
logMessage Script $0 finished
