#!/bin/sh
#
#  This script cleans the yum database on the new system.
#
# Steve
# --
# http://www.steve.org.uk/


TARGET=$1

#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Clean up RPM files.
#
logMessage Cleaning .rpm* files.
find ${TARGET}/ -name '*.rpmorig' -exec rm -f \{\} \;
find ${TARGET}/ -name '*.rpmnew' -exec rm -f \{\} \;

#
#  Clean yum
#
logMessage Cleaning Yum Repository

if [ ! -d ${TARGET}/proc ]; then
    mkdir -p ${TARGET}/proc
fi
mount -o bind /proc ${TARGET}/proc
chroot ${TARGET} /usr/bin/yum clean all
umount ${TARGET}/proc

#
#  Log our finish
#
logMessage Script $0 finished
