#!/bin/sh
#
#  Configure the new image to be suitable for compiling Debian packages within
#
# Steve
# --
# http://www.steve.org.uk/
#


TARGET=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi





#
#  Update APT lists.
#
chroot ${TARGET} /usr/bin/apt-get update


#
#  Install the packages
#
installDebianPackage ${TARGET} dpkg-dev
installDebianPackage ${TARGET} devscripts
installDebianPackage ${TARGET} fakeroot
installDebianPackage ${TARGET} debhelper
installDebianPackage ${TARGET} build-essential
installDebianPackage ${TARGET} lintian
installDebianPackage ${TARGET} linda
