#!/bin/sh
#
#  This role installs CFengine upon the new guest system.
#
#  It must make sure that the server is not running before it exits 
# otherwise the temporary mounted directory will not be unmountable.
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi



#
# Log our start
#
logMessage Script $0 starting


#
#  Install CFengine
#
installDebianPackage ${prefix} cfengine2


#
#  Make sure the CFengine server isn't running, this will cause our
# unmounting of the disk image to fail..
#
chroot ${prefix} /etc/init.d/cfengine2 stop

#
#  Copy cfengine update.conf & defaults from Dom0
#
cp /etc/cfengine/update.conf ${prefix}/etc/cfengine/
cp /etc/default/cfengine2 ${prefix}/etc/default/

#
#  Log our finish
#
logMessage Script $0 finished
