#!/bin/sh
#
#  Configure the new image to be a minimal image, by removing
# packages I don't care about - and installing new ones I prefer.
#
# Steve
# --
# http://www.steve.org.uk/
#


TARGET=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi




#
#  Install some new packages - do this first to avoid dependency errors.
#
installDebianPackage ${TARGET} syslog-ng 
installDebianPackage ${TARGET} deborphan
installDebianPackage ${TARGET} less
installDebianPackage ${TARGET} screen
installDebianPackage ${TARGET} sudo
installDebianPackage ${TARGET} vim


#
#  Remove some standard packages.
#

# PPP stuff.
removeDebianPackage ${TARGET} pppconfig
removeDebianPackage ${TARGET} pppoeconf
removeDebianPackage ${TARGET} pppoe
removeDebianPackage ${TARGET} ppp
removeDebianPackage ${TARGET} libpcap0.7

# Editors
removeDebianPackage ${TARGET} nano
removeDebianPackage ${TARGET} ed
removeDebianPackage ${TARGET} nvi

# Syslog
removeDebianPackage ${TARGET} klogd
removeDebianPackage ${TARGET} sysklogd

# manpages
removeDebianPackage ${TARGET} manpages  
removeDebianPackage ${TARGET} man-db 
removeDebianPackage ${TARGET} info

# misc
removeDebianPackage ${TARGET} tasksel tasksel-data
removeDebianPackage ${TARGET} pciutils
removeDebianPackage ${TARGET} fdutils
removeDebianPackage ${TARGET} cpio
