#!/bin/sh
#
#  Configure the new image to have udev installed.
#
# Steve
# --
# http://www.steve.org.uk/
#


TARGET=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi


#
#  Install udev.
#
installDebianPackage ${TARGET} udev


#
#  Update APT lists.
#
chroot ${TARGET} /usr/bin/apt-get update

