#!/bin/sh
#
#  Configure the new image to be a XDM VNC server.
#
# Steve
# --
# http://www.steve.org.uk/
#


prefix=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi




#
#  Update APT lists.
#
chroot ${prefix} /usr/bin/apt-get update

#
#  Install the packages
#
installDebianPackage ${prefix} xserver-xfree86
installDebianPackage ${prefix} vncserver
installDebianPackage ${prefix} xfonts-100dpi
installDebianPackage ${prefix} xfonts-75dpi
installDebianPackage ${prefix} xfonts-base
installDebianPackage ${prefix} rxvt
installDebianPackage ${prefix} xdm
installDebianPackage ${prefix} icewm-experimental


#
#  Remove the default settings.
#
rm ${prefix}/etc/X11/xdm/Xserver
rm ${prefix}/etc/X11/xdm/Xservers

#
#  Setup XDM to use the VNC server we installed.
#
/bin/echo ':0 /usr/bin/Xvnc /usr/bin/Xvnc -geometry 1024x768 -depth 24' > \
  ${prefix}/etc/X11/xdm/Xservers
