#!/bin/sh
#
#  Configure the new image to be a XDM VNC server.
#
# Steve
# --
# http://www.steve.org.uk/
#


TARGET=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi




#
#  Update APT lists.
#
chroot ${TARGET} /usr/bin/apt-get update

#
#  Install the packages
#
installDebianPackage ${TARGET} xserver-xfree86
installDebianPackage ${TARGET} vncserver
installDebianPackage ${TARGET} xfonts-100dpi
installDebianPackage ${TARGET} xfonts-75dpi
installDebianPackage ${TARGET} xfonts-base
installDebianPackage ${TARGET} rxvt
installDebianPackage ${TARGET} xdm
installDebianPackage ${TARGET} icewm-experimental


#
#  Remove the default settings.
#
rm ${TARGET}/etc/X11/xdm/Xserver
rm ${TARGET}/etc/X11/xdm/Xservers

#
#  Setup XDM to use the VNC server we installed.
#
/bin/echo ':0 /usr/bin/Xvnc /usr/bin/Xvnc -geometry 1024x768 -depth 24' > \
  ${TARGET}/etc/X11/xdm/Xservers
