#!/bin/sh
#
#  This script comments out all virtual terminals which aren't on the
# first console - that must remain so that 'xm console ...' works
# correctly.
#


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Switch off the gettys for everything other than tty1.
#

# SYSV based init scripts
if [ -f ${prefix}/etc/inittab ]; then
    logMessage SYSV init system detected. Fixing-up inittab.
    sed -i -e 's/^\([2-6].*:respawn*\)/#\1/' -e 's/^T/#\t/' ${prefix}/etc/inittab
fi

# Upstart based init systems 
if [ -f ${prefix}/etc/event.d/tty2 ]; then
    logMessage Upstart init system detected. Disabling tty control files.
    rm ${prefix}/etc/event.d/tty[^1]
fi

#
#  Log our finish
#
logMessage Script $0 finished
