#!/bin/sh
#
#  Configure the new image to be suitable for compiling Debian packages within
#
# Steve
# --
# http://www.steve.org.uk/
#
# $Id: builder,v 1.1 2006-02-05 18:10:34 steve Exp $


prefix=$1



#
#  This function installs a single package into the chroot, forcing
# the installation to be non-interactive.
#
function install_package
{
    package=$1
    
    DEBIAN_FRONTEND=noninteractive chroot ${prefix} /usr/bin/apt-get --yes --force-yes install $package

}




#
#  Update APT lists.
#
chroot ${prefix} /usr/bin/apt-get update

#
#  Install the packages
#
install_package dpkg-dev
install_package devscripts
install_package fakeroot
install_package debhelper
install_package build-essential
install_package lintian
install_package linda
