#!/usr/bin/perl -w -I..
#
#  Test that all the Perl modules we require are available.
#
#  This list is automatically generated by modules.sh
#
# Steve
# --
# $Id: modules.t,v 1.6 2006-01-02 14:05:58 steve Exp $
#

use Test::More qw( no_plan );

BEGIN{ use_ok( 'English' ); }
require_ok( 'English' );


BEGIN{ use_ok( 'File::Copy' ); }
require_ok( 'File::Copy' );


BEGIN{ use_ok( 'File::Temp' ); }
require_ok( 'File::Temp' );


BEGIN{ use_ok( 'Getopt::Long' ); }
require_ok( 'Getopt::Long' );


BEGIN{ use_ok( 'IPC::Open3' ); }
require_ok( 'IPC::Open3' );


BEGIN{ use_ok( 'Pod::Usage' ); }
require_ok( 'Pod::Usage' );


BEGIN{ use_ok( 'strict' ); }
require_ok( 'strict' );


BEGIN{ use_ok( 'Test::More' ); }
require_ok( 'Test::More' );


