#!/bin/sh
#
#  This script disables TLS on the new image.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1

mv ${prefix}/lib/tls ${prefix}/lib/tls.disabled

#
#  Make a new /lib/tls directory in the guest, and make sure
# it cannot be modified.
#
mkdir     ${prefix}/lib/tls
