#!/bin/sh
#
#  This script disables TLS on the new image.
#
# Steve
# --
# http://www.steve.org.uk/



prefix=$1
dist=$2


#
#  This script doesn't do anything different on a per-distribution basis
#



mv ${prefix}/lib/tls ${prefix}/lib/tls.disabled
mkdir ${prefix}/lib/tls
