#!/bin/sh
#
#  This script disables the hardware clock.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1
dist=$2



#
#  Disable the startup scripts from all runlevels.
#
function setupDebian
{
    chmod -x ${prefix}/etc/init.d/hwclock.sh
    chmod -x ${prefix}/etc/init.d/hwclockfirst.sh
}



#
#  Entry point to the script.
#
case "${dist}" in
    sarge|etch|sid)
        setupDebian
        ;;
    *)
	echo "Unknown distribution '${dist}'.  Fixme";
	exit;
	;;
esac




