#!/bin/sh
#
#  This script does two things:
#
#  1. Sets the console type for the first terminal to 'console'.
#  2. Comments out all virtual terminals which aren't on the first console.
#
# Steve
# --
# http://www.steve.org.uk/

prefix=$1

cat /etc/inittab | \
  sed "s/tty[0-9]$/console/g" | \
  sed "s/^\([2-6].*:respawn*\)/#\1/" \
  > ${prefix}/etc/inittab

