#!/bin/sh
#
#  This script does two things:
#
#  Comments out all virtual terminals which aren't on the first console.
#  Sets the console type for the first terminal to 'console'.
#

prefix=$1

cat /etc/inittab | \
  sed "s/tty1$/console/g" | \
  sed "s/^\([2-6].*:respawn*\)/#\1/" \
  > ${prefix}/etc/inittab

