#!/bin/sh
#
#  This script ensures that the new guest images have a nicely
# populated /dev directory.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1

#
#  Make sure we have a /dev directory and change into it.
#
mkdir -p ${prefix}/dev
cd ${prefix}/dev

#
# Make the devices.
#
if [ "${rpmstrap}" ]; then
    chroot ${prefix} /bin/sh -c 'cd /dev && ./MAKEDEV console'
    chroot ${prefix} /bin/sh -c 'cd /dev && ./MAKEDEV null'
    chroot ${prefix} /bin/sh -c 'cd /dev && ./MAKEDEV zero'
else
    ./MAKEDEV generic
fi