#!/bin/sh
#
#  This script copies "essential" files from the host to the new
# system.
#
# Steve
# --
# $Id: 60-copy-host-files,v 1.6 2006-02-05 14:53:27 steve Exp $



prefix=$1

cp /etc/resolv.conf ${prefix}/etc/
cp /etc/passwd      ${prefix}/etc/
cp /etc/shadow      ${prefix}/etc/
cp /etc/group       ${prefix}/etc/
cp /etc/gshadow     ${prefix}/etc/

#
# If sudo is installed upon the host then install it upon the guest.
#
if [ -e /etc/sudoers ]; then
    cp /etc/sudoers ${prefix}/etc/
    chmod 440 ${prefix}/etc/sudoers
    DEBIAN_FRONTEND=noninteractive chroot ${prefix} /usr/bin/apt-get --yes --force-yes install sudo
fi

