#!/bin/sh
#
#  Copy files from a 'skel' directory, if present, into the
# new images
#


prefix=$1
dist=$2


#
#  This script doesn't do anything different on a per-distribution basis
#



if [ -d /etc/xen-tools/skel ]; then

   #
   #  Copy everything from skel directory, even "dotfiles".
   #
   (cd /etc/xen-tools/skel; tar -cf - . ) | (cd ${prefix}/; tar -xpf -)

else

   echo "skel directory not present, ignoring."

fi
