#!/bin/sh
#
#  This script installs OpenSSH upon the new system.
#
# Steve
# --
# $Id: 70-install-ssh,v 1.3 2005-12-25 02:16:00 steve Exp $


prefix=$1

chroot ${prefix} /usr/bin/apt-get update
DEBIAN_FRONTEND=noninteractive chroot ${prefix} /usr/bin/apt-get --yes --force-yes install ssh
chroot ${prefix} /etc/init.d/ssh stop
