#!/bin/sh
#
#  This script installs OpenSSH upon the new system.
#
# Steve
# --
# $Id: 70-install-ssh,v 1.5 2006-02-05 14:53:35 steve Exp $


prefix=$1

#
#  This function installs a package upon the guest image.
#
function install_package
{
    package=$1
    
    DEBIAN_FRONTEND=noninteractive chroot ${prefix} /usr/bin/apt-get --yes --force-yes install $package

}



#
# Install the package.
#
install_package ssh

#
#  Make sure sshd isn't running, this will cause our unmounting of the
# disk image to fail..
#
chroot ${prefix} /etc/init.d/ssh stop
