#!/bin/sh
#
#  Install modules from the host system into the new image, and
# ensure that 'module-init-tools' is setup.
#
#


#
#  The virtual image is mounted here.
#
prefix=$1

#
#  Copy the modules from the host to the new system - we should only
# really copy the *correct* modules, but we don't know what they are.
#
mkdir -p ${prefix}/lib/modules
cp -R /lib/modules/*/ ${prefix}/lib/modules

#
#  Now install the 'module-init-tools'.
#
DEBIAN_FRONTEND=noninteractive chroot $prefix /usr/bin/apt-get --yes --force-yes install module-init-tools
