#!/bin/sh 
#
#  This script is responsible for setting up the Xen Configuration file
# 
# Steve
# --
# http://www.steve.org.uk/


prefix=$1

#
#  Useful hook for testing.
#
output_dir=/etc/xen

if [ "${testing}" ]; then
    if [ -d ${testing_dir} ]; then
	output_dir=${testing_dir}
    fi
fi


#
# Make sure we use ide style device names if required
#
device=sda
if [ "${use-ide}" ]; then
    device=hda
fi

if [ "${dhcp}" ]; then
    dyn='dhcp = "dhcp"'
else
    dyn="vif = ['ip=${ip}']"
fi

echo "Creating Xen configuration file in /etc/xen .. "

cat <<E_O_CFG > ${output_dir}/${hostname}.cfg
kernel  = '${kernel}'
ramdisk = '${initrd}'
memory  = ${memory}
name    = '${hostname}'
root    = '/dev/${device}1 ro'
disk    = [ '${imagevbd},${device}1,w', '${swapvbd},${device}2,w' ]
${dyn}

E_O_CFG
