#!/bin/sh
#
#  This script runs 'apt-get clean' on the freshly created image,
# to make sure it has the maximum available amount of free space.
#
# Steve
# --
# $Id: 99-clean-image,v 1.5 2006-03-11 21:11:56 steve Exp $


prefix=$1

chroot ${prefix} /usr/bin/apt-get clean

