#!/bin/sh
#
#  This script disables the hardware clock.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1


#
#  Source our common functions
#
if [ -e ../common.sh ]; then
    . ../common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Disable the startup scripts from all runlevels.
#
chmod -x ${prefix}/etc/init.d/hwclock.sh
chmod -x ${prefix}/etc/init.d/hwclockfirst.sh



#
# Log our finish
#
logMessage Script $0 finished.