#!/bin/sh
#
#  This script ensures that the new guest images have a nicely
# populated /dev directory.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1


#
#  Source our common functions
#
if [ -e ../common.sh ]; then
    . ../common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Make the device nodes.
#
cd ${prefix}/dev
./MAKEDEV generic


#
#  Log our finish
#
logMessage Script $0 finished
