#!/bin/sh
#
#  This script installs CFengine upon the new system, if it is also
# installed on the Dom0.
#
#  It must make sure that the server is not running before it exits 
# otherwise the temporary mounted directory will not be unmountable.
#


prefix=$1

#
#  Exit if cfagent is not installed
#
if [ ! -e /usr/sbin/cfagent ]; then
    exit
fi

#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Install ssh
#
installDebianPackage ${prefix} cfengine2


#
#  Make sure sshd isn't running, this will cause our unmounting of the
# disk image to fail..
#
chroot ${prefix} /etc/init.d/cfengine2 stop

#
#  Copy cfengine update.conf & defaults from Dom0
#
cp /etc/cfengine/update.conf ${prefix}/etc/cfengine/
cp /etc/default/cfengine2 ${prefix}/etc/default/

#
#  Log our finish
#
logMessage Script $0 finished
