#!/bin/sh
#
#  This script ensures the new image has locales setup correctly.
#
# Steve
# --
# http://www.steve.org.uk/

TARGET=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Default to the same locale as the host.
#
if [ -e /etc/locale.gen ]; then
   cp /etc/locale.gen ${TARGET}/etc
fi

#
#  Install the package
#
installDebianPackage ${TARGET} locales
installDebianPackage ${TARGET} util-linux-locales
chroot ${TARGET} /usr/sbin/update-locale LANG=C


#
# Log our finish
#
logMessage Script $0 finished.
