#!/bin/sh
#
#  This script allows all users to use 'su' to become root.
#
# Steve
# --
# http://www.steve.org.uk/


TARGET=$1

#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting

#
# Remove lines matching 'group' or 'wheel'.
#
grep -v wheel ${TARGET}/etc/pam.d/su     > ${TARGET}/etc/pam.d/su.tmp
grep -v group ${TARGET}/etc/pam.d/su.tmp > ${TARGET}/etc/pam.d/su

#
# Make sure permissions are correct.
#
chown root:root ${TARGET}/etc/pam.d/su
chmod 600       ${TARGET}/etc/pam.d/su

#
#  Log our finish
#
logMessage Script $0 finished
