#!/bin/sh
#
#  This script installs OpenSSH upon the new system.
#
#  It must make sure that the server is not running before it exits 
# otherwise the temporary mounted directory will not be unmountable.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Install ssh
#
installGentooPackage ${prefix} ssh


#
#  Make sure sshd isn't running, this will cause our unmounting of the
# disk image to fail..
#
chroot ${prefix} /etc/init.d/ssh stop


#
#  Log our finish
#
logMessage Script $0 finished
