#!/bin/sh

set -e

for dist in $(awk '!/^#|^$|dont-test/ {print $1}' /etc/xen-tools/distributions.conf); do
    xen-create-image --dist $dist --hostname "xen-tools-release-testing-$dist" --force --verbose "$@"
done 2>&1 | tee xen-tools-release-testing.log
