#!/bin/sh
#
#  This script disables TLS
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Ignore tls on 64 bit machines.
#
if [ "`uname -m`" = "x86_64" ]; then

    logMessage "Ignoring TLS since we're a 64 bit host."

else

    logMessage "Disabling TLS"
    mv ${prefix}/lib/tls ${prefix}/lib/tls.disabled
    mkdir ${prefix}/lib/tls
fi



#
#  Log our finish
#
logMessage Script $0 finished
